### ISSUE TITLE
Fail gracefully when no network connection

### ISSUE THREAD

**Issue by dbrnz** [AnatomicMaps/map-knowledge#17]
Mapmaker gets the following from map-knowledge when there is no network connection. It would be better to log the fact that GitHub can't be reached and note that ApiNATOMY knowledge won't be retrieved.

```
2023-12-08 12:11:40,282 ERROR: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /SciCrunch/NIF-Ontology/neurons/ttl/generated/neurons/apinat-partial-orders.ttl (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x136d588e0>: Failed to resolve 'raw.githubusercontent.com' ([Errno 8] nodename nor servname provided, or not known)"))
Traceback (most recent call last):
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/Users/dbro078/.pypoetry/virtualenvs/mapmaker-jbbtoRZc-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x136d588e0>: Failed to resolve 'raw.githubusercontent.com' ([Errno 8] nodename nor servname provided, or not known)
```

**Comment by dbrnz** [comment]
Part of PR #21.
